### ISSUE TITLE
数据集的组织方式

### ISSUE THREAD

**Issue by derekshiii** [HiLab-git/UPL-SFDA#1]
你好，我在复现数据集时，按照Readme.md中的方式组织数据集，但是复现时会出现如下报错，怀疑是数据集的组织方式有误，希望请您解答下
![image](https://github.com/HiLab-git/UPL-SFDA/assets/102472253/b9257e06-44b6-4c8d-a317-c0b8574d4a2f)
```
Traceback (most recent call last):
  File "/content/drive/MyDrive/UPL-SFDA-main/train_source.py", line 131, in <module>
    mian()
  File "/content/drive/MyDrive/UPL-SFDA-main/train_source.py", line 116, in mian
    list_data = train(config,train_loader,valid_loader,test_loader,target,list_data)
  File "/content/drive/MyDrive/UPL-SFDA-main/train_source.py", line 68, in train
    for it,(xt,xt_label,xt_name,lab_Imag) in enumerate(valid_loader):  
  File "/usr/local/lib/python3.10/dist-packages/torch/utils/data/dataloader.py", line 630, in __next__
    data = self._next_data()
  File "/usr/local/lib/python3.10/dist-packages/torch/utils/data/dataloader.py", line 674, in _next_data
    data = self._dataset_fetcher.fetch(index)  # may raise StopIteration
  File "/usr/local/lib/python3.10/dist-packages/torch/utils/data/_utils/fetch.py", line 51, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/usr/local/lib/python3.10/dist-packages/torch/utils/data/_utils/fetch.py", line 51, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/content/drive/MyDrive/UPL-SFDA-main/utils.py", line 334, in __getitem__
    A,A_gt = resize(A,A_gt)
  File "/content/drive/MyDrive/UPL-SFDA-main/utils.py", line 285, in resize
    D,H,W = img.shape
ValueError: too many values to unpack (expected 3)
```

**Comment by JianghaoWu** [comment]
需要注意你的数据集是2D还是3D/4D，这个报错是数据集的维度不对导致的。给出的代码数据集是3D 作为输入，而你的数据集如果是使用的原始MMS数据集，则可能是4D （多了一个时间维度）。

**Comment by derekshiii** [comment]
特别感谢你的回答！我是直接将时间维度取平均，想请问您是如何处理原始MMS数据集的，特别感谢！！！

**Comment by JianghaoWu** [comment]
MMS数据集一共有4个维度，其中第一个是时间维度，不是所有的时间都带有标注。在一个4维volume中，可以根据label的内容选择出有标注的3维volume（只需要判断label是否为空即可），并将对应的3D image和3D label分别保存成常规的3D volume。

**Comment by derekshiii** [comment]
谢谢！！特别感谢！祝科研顺利！
